name: Bilibili
on:
  push:
  schedule:
    - cron: "0 22 * * *"

jobs:
  _BILIBLI:
    runs-on: windows-2019
    steps:
      - name: checkout actions
        uses: actions/checkout@v3

      - name: init python
        uses: actions/setup-python@v4
        with:
          python-version: 3.7.4
          cache: "pip" # caching pip dependencies
      - name: pip
        run: |
          cd src
          pip install -r requirements.txt

      - name: init
        env:
          cookie: ${{ secrets.COOKIE }}
        run: |
          cd src
          python index.py ${env:cookie}
