name: Bilibili
on:
  push:
  schedule:
    - cron: "0 22 * * *"

jobs:
  _BILIBLI:
    runs-on: windows-2019
    steps:
      - name: checkout actions
        uses: actions/checkout@v1

      - name: Python 3.7.4
        with:
          python-version: 3.7.4
          cache: 'pip' # caching pip dependencies
        run: pip install -r requirements.txt

      - name: init
        env:
          cookie: ${{ secrets.COOKIE }}
        run: |
          cd src
          python index.py ${cookie}
